### ISSUE TITLE
error when install 

### ISSUE THREAD

**Issue by Andlinks-Yourturn** [ipfs/go-ipld-eth#14]
Hi,
   I have met some problem when building go-ipld-eth as a  plugin. Here are the errors:

 **cannot use d (type "gx/ipfs/QmVSase1JP7cq9QkPT46oNwdp9pT6kBkG3oqS14y3QcZjG/go-
 datastore".Batching) as type "github.com/ipfs/go-datastore".Datastore in argument to namespace.Wrap**

I thought it's something about gx tools. But, i do not know how to solve it.
So,  anyone can help
ThankU

**Comment by hermanjunge** [comment]
Install `gx-go` and do `gx-go rw` before building, it should transform your dependencies accordingly.
