### ISSUE TITLE
Add go.mod for dependency management.

### ISSUE THREAD

**Issue by arijitAD** [ipfs/go-ipld-eth#15]

**Comment by BigLep** [comment]
@rvagg @warpfork : I believe this repo is dead.  A couple things:
1. Can you please confirm?
2. Can you point @arijitAD to the new repo?
3. Can we please archive this one?

**Comment by rvagg** [comment]
https://github.com/vulcanize/go-codec-dageth

we should properly archive this repo now and link to that

**Comment by BigLep** [comment]
Please use https://github.com/vulcanize/go-codec-dageth .  This repo is archived now.  Thanks.
